### ISSUE TITLE
Develop is broken

### ISSUE THREAD

**Issue by rscherrer** [rscherrer/ExplicitGenomeSpeciation#37]
@thijsjanzen I changed something in the Collector::analyze function, which now takes one extra argument. I see that it broke the build because it is still the old version, with fewer arguments, that is called in your code. I corrected this on my branch, now just waiting for Travis to be done, but hopefully the build will pass and I'll merge to develop. If you bring your branch up to date with develop after this is done, the problem should be fixed!

(It's also a very simple fix, so if you do it independently on your branch I think that's fine. It's about adding argument "arch" to the analyze function, in addition to "metapop" and "pars".)

**Comment by thijsjanzen** [comment]
I noticed, no worries!

**Comment by rscherrer** [comment]
Okay, now the run is taking too long, causing the build to time out. I'll reduce the default number of generations to 10 with no burnin!
